apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ot-digital-twin

resources:
- api-deployment.yaml
- unity-deployment.yaml

commonLabels:
  project: ot-digital-twin
  managed-by: kustomize
  team: i3-technologies
